project:
  type: website
  output-dir: docs

website:
  title: "Test Quarto Site"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Different
      - href: another_one.qmd
        text: Another One
      - text: Menu
        menu:
          - href: menu_1.qmd
            text: Menu 1
          - href: menu_2.qmd
            text: Menu 2
          - href: menu_3.qmd
            text: Menu 3
          - href: menu_4.qmd
            text: Menu 4

format:
  html:
    theme: united
    css: styles.css
    toc: true

editor: source

